### ISSUE TITLE
500 http error on basic request to pull countries

### ISSUE THREAD

**Issue by p-drolima** [didww/php-sdk#5]
Hi Igor,

Working on implementing a simple display of countries and cities but not familiar with SDK.

Currently I am getting a 500 http error when I call 

use Didww\API2\Country;
var_dump(Country::getAll());

I am requiring autoload.php before the API credentials and connection seems to got through but once I call API to get countries I get the error.

Look forward to your help.

Thank you,

Pedro

**Comment by Fivell** [comment]
@p-drolima , are you using sandbox or production?  what is your API username ?

**Comment by Fivell** [comment]
generally your code should look like

```php
 $userName = "user@gmail";
 $password = "44AEIRTCH5NE2MAPDXYGKHJHH";
 $testMode = false; #or true for sandbox
 use Didww\API2\ApiCredentials, Didww\API2\ApiClient as Client;
 use Didww\API2\Country;
 Client::setCredentials(new ApiCredentials($userName,$password,$testMode));
 Client::setDebug(true); #will write detailed error log
 $countries = Country::getAll();
 var_dump($countries);
```

if still getting error, please share error_log

**Comment by p-drolima** [comment]
I am using sandbox. API username is jwechsler@hushmail.com

last 15 minutes of error.log

`[Fri Jan 13 06:37:26.821690 2017] [ssl:warn] [pid 993] AH01909: 64.251.26.132:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jan 13 06:37:26.825996 2017] [mpm_prefork:notice] [pid 993] AH00163: Apache/2.4.10 (Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
[Fri Jan 13 06:37:26.826008 2017] [core:notice] [pid 993] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jan 13 07:20:23.904514 2017] [:error] [pid 22651] [client 77.72.4.10:34685] script '/var/www/html/joomla/deleteme.chavv6ad.php' not found or unable to stat
[Fri Jan 13 07:20:24.279326 2017] [:error] [pid 22689] [client 77.72.4.10:34687] script '/var/www/html/joomla/deleteme.chavv6ad.php' not found or unable to stat
[Fri Jan 13 07:20:24.839748 2017] [:error] [pid 22650] [client 77.72.4.10:34700] script '/var/www/html/joomla/deleteme.cha59lbp.php' not found or unable to stat
[Fri Jan 13 07:20:25.202695 2017] [:error] [pid 22648] [client 77.72.4.10:34712] script '/var/www/html/joomla/deleteme.cha59lbp.php' not found or unable to stat
[Fri Jan 13 07:20:25.742043 2017] [:error] [pid 22649] [client 77.72.4.10:34718] script '/var/www/html/joomla/deleteme.chapicz8.php' not found or unable to stat
[Fri Jan 13 07:20:26.111377 2017] [:error] [pid 22652] [client 77.72.4.10:34729] script '/var/www/html/joomla/deleteme.chapicz8.php' not found or unable to stat
[Fri Jan 13 10:59:53.686413 2017] [:error] [pid 23809] [client 176.79.169.130:62139] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/index.php on line 36
[Fri Jan 13 11:00:02.237645 2017] [:error] [pid 23259] [client 176.79.169.130:65110] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/index.php on line 36
[Fri Jan 13 11:00:23.800852 2017] [:error] [pid 23478] [client 176.79.169.130:58614] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/index.php on line 36
[Fri Jan 13 11:00:25.646520 2017] [:error] [pid 22652] [client 176.79.169.130:62542] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/index.php on line 36
[Fri Jan 13 11:02:10.698188 2017] [:error] [pid 23478] [client 176.79.169.130:57826] script '/var/www/html/joomla/test.php' not found or unable to stat
[Fri Jan 13 11:02:26.802059 2017] [:error] [pid 23471] [client 176.79.169.130:51164] script '/var/www/html/joomla/test.php' not found or unable to stat
[Fri Jan 13 11:02:27.666370 2017] [:error] [pid 23471] [client 176.79.169.130:51164] script '/var/www/html/joomla/test.php' not found or unable to stat
[Fri Jan 13 11:02:28.444745 2017] [:error] [pid 23471] [client 176.79.169.130:51164] script '/var/www/html/joomla/test.php' not found or unable to stat
[Fri Jan 13 11:02:39.173159 2017] [:error] [pid 22648] [client 176.79.169.130:57086] script '/var/www/html/joomla/templates/test.php' not found or unable to stat
[Fri Jan 13 11:03:02.342609 2017] [:error] [pid 23809] [client 176.79.169.130:51428] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/test.php on line 7
[Fri Jan 13 11:03:10.561345 2017] [:error] [pid 23456] [client 176.79.169.130:58816] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/test.php on line 7
[Fri Jan 13 11:04:26.488611 2017] [:error] [pid 22649] [client 176.79.169.130:61034] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/test.php on line 7
[Fri Jan 13 11:04:29.889445 2017] [:error] [pid 23873] [client 176.79.169.130:61692] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/test.php on line 7
[Fri Jan 13 11:07:06.764939 2017] [:error] [pid 22651] [client 176.79.169.130:56144] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php on line 7
[Fri Jan 13 11:07:08.592218 2017] [:error] [pid 23259] [client 176.79.169.130:62644] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php on line 7
[Fri Jan 13 11:07:09.607092 2017] [:error] [pid 23478] [client 176.79.169.130:57434] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php on line 7
[Fri Jan 13 11:07:40.893557 2017] [:error] [pid 23471] [client 176.79.169.130:49331] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php on line 7
[Fri Jan 13 11:07:42.340387 2017] [:error] [pid 23809] [client 176.79.169.130:56064] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php on line 7
[Fri Jan 13 11:07:43.494167 2017] [:error] [pid 23456] [client 176.79.169.130:57196] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php on line 7
[Fri Jan 13 11:07:57.472664 2017] [:error] [pid 22649] [client 176.79.169.130:63793] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php on line 7
[Fri Jan 13 11:07:58.681670 2017] [:error] [pid 23873] [client 176.79.169.130:63134] PHP Fatal error:  Class 'Didww\\API2\\ApiClient' not found in /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php on line 7
[Fri Jan 13 11:12:30.326016 2017] [:error] [pid 23259] [client 176.79.169.130:62916] DIDWWApiClient debug. raw request  <?xml version="1.0" encoding="UTF-8"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:didww" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:didww_getdidwwcountries><auth_string xsi:type="xsd:string">0134e82efd1b25098ae733e903ae0dbf838a009a</auth_string><country_iso xsi:nil="true"/></ns1:didww_getdidwwcountries></SOAP-ENV:Body></SOAP-ENV:Envelope>\n
[Fri Jan 13 11:12:30.326077 2017] [:error] [pid 23259] [client 176.79.169.130:62916] DIDWWApiClient debug. raw response  <?xml version="1.0" encoding="ISO-8859-1"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"\n    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:didww"\n    SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">\n    <SOAP-ENV:Body>\n        <SOAP-ENV:Fault>\n    <faultcode xsi:type="xsd:string">100</faultcode>\n    <faultstring xsi:type="xsd:string">Access denied</faultstring>\n    <faultactor xsi:type="xsd:string"/>\n    <detail xsi:type="xsd:string"/>\n</SOAP-ENV:Fault>\n    </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>
[Fri Jan 13 11:12:30.326124 2017] [:error] [pid 23259] [client 176.79.169.130:62916] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/test.php(8): Didww\\API2\\Country::getAll()\n#3 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:13:14.274087 2017] [:error] [pid 23478] [client 176.79.169.130:60283] DIDWWApiClient debug. raw request  <?xml version="1.0" encoding="UTF-8"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:didww" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:didww_getdidwwcountries><auth_string xsi:type="xsd:string">0134e82efd1b25098ae733e903ae0dbf838a009a</auth_string><country_iso xsi:nil="true"/></ns1:didww_getdidwwcountries></SOAP-ENV:Body></SOAP-ENV:Envelope>\n
[Fri Jan 13 11:13:14.274167 2017] [:error] [pid 23478] [client 176.79.169.130:60283] DIDWWApiClient debug. raw response  <?xml version="1.0" encoding="ISO-8859-1"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"\n    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:didww"\n    SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">\n    <SOAP-ENV:Body>\n        <SOAP-ENV:Fault>\n    <faultcode xsi:type="xsd:string">100</faultcode>\n    <faultstring xsi:type="xsd:string">Access denied</faultstring>\n    <faultactor xsi:type="xsd:string"/>\n    <detail xsi:type="xsd:string"/>\n</SOAP-ENV:Fault>\n    </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>
[Fri Jan 13 11:13:14.274216 2017] [:error] [pid 23478] [client 176.79.169.130:60283] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php(16): Didww\\API2\\Country::getAll()\n#3 /var/www/html/joomla/templates/jsn_teki_free/test.php(4): include_once('/var/www/html/j...')\n#4 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:13:16.351010 2017] [:error] [pid 23456] [client 176.79.169.130:51498] DIDWWApiClient debug. raw request  <?xml version="1.0" encoding="UTF-8"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:didww" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:didww_getdidwwcountries><auth_string xsi:type="xsd:string">0134e82efd1b25098ae733e903ae0dbf838a009a</auth_string><country_iso xsi:nil="true"/></ns1:didww_getdidwwcountries></SOAP-ENV:Body></SOAP-ENV:Envelope>\n
[Fri Jan 13 11:13:16.351073 2017] [:error] [pid 23456] [client 176.79.169.130:51498] DIDWWApiClient debug. raw response  <?xml version="1.0" encoding="ISO-8859-1"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"\n    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:didww"\n    SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">\n    <SOAP-ENV:Body>\n        <SOAP-ENV:Fault>\n    <faultcode xsi:type="xsd:string">100</faultcode>\n    <faultstring xsi:type="xsd:string">Access denied</faultstring>\n    <faultactor xsi:type="xsd:string"/>\n    <detail xsi:type="xsd:string"/>\n</SOAP-ENV:Fault>\n    </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>
[Fri Jan 13 11:13:16.351120 2017] [:error] [pid 23456] [client 176.79.169.130:51498] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php(16): Didww\\API2\\Country::getAll()\n#3 /var/www/html/joomla/templates/jsn_teki_free/test.php(4): include_once('/var/www/html/j...')\n#4 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:24:58.913555 2017] [:error] [pid 23809] [client 176.79.169.130:52038] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/test.php(8): Didww\\API2\\Country::getAll()\n#3 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:25:26.561022 2017] [:error] [pid 23539] [client 176.79.169.130:61066] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/test.php(8): Didww\\API2\\Country::getAll()\n#3 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:32:44.707618 2017] [:error] [pid 23873] [client 176.79.169.130:50410] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php(15): Didww\\API2\\Country::getAll()\n#3 /var/www/html/joomla/templates/jsn_teki_free/test.php(4): require_once('/var/www/html/j...')\n#4 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:32:49.391105 2017] [:error] [pid 23539] [client 176.79.169.130:64583] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php(15): Didww\\API2\\Country::getAll()\n#3 /var/www/html/joomla/templates/jsn_teki_free/test.php(4): require_once('/var/www/html/j...')\n#4 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:33:09.549688 2017] [:error] [pid 23809] [client 176.79.169.130:65013] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php(15): Didww\\API2\\Country::getAll()\n#3 /var/www/html/joomla/templates/jsn_teki_free/test.php(4): require_once('/var/www/html/j...')\n#4 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:33:11.959533 2017] [:error] [pid 23478] [client 176.79.169.130:52706] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php(15): Didww\\API2\\Country::getAll()\n#3 /var/www/html/joomla/templates/jsn_teki_free/test.php(4): require_once('/var/www/html/j...')\n#4 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211
[Fri Jan 13 11:33:24.560156 2017] [:error] [pid 23456] [client 176.79.169.130:52862] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php(15): Didww\\API2\\Country::getAll()\n#3 /var/www/html/joomla/templates/jsn_teki_free/test.php(4): require('/var/www/html/j...')\n#4 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211`

**Comment by p-drolima** [comment]
seem a 100 error access denied. obvious question is, why?

**Comment by p-drolima** [comment]
sorry I think last part of log, had setDebug to false. Here is one request in log with it as true:

`[Fri Jan 13 11:42:44.978371 2017] [:error] [pid 23478] [client 176.79.169.130:50230] PHP Fatal error:  Uncaught SoapFault exception: [100] Access denied in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php:211\nStack trace:\n#0 /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php(211): SoapClient->__soapCall('didww_getdidwwc...', Array)\n#1 /var/www/html/joomla/didww-sdk/src/Didww/API2/Country.php(297): Didww\\API2\\ApiClient->call('getdidwwcountri...', Array)\n#2 /var/www/html/joomla/templates/jsn_teki_free/APICredentials.php(15): Didww\\API2\\Country::getAll()\n#3 /var/www/html/joomla/templates/jsn_teki_free/test.php(4): require('/var/www/html/j...')\n#4 {main}\n  thrown in /var/www/html/joomla/didww-sdk/src/Didww/API2/ApiClient.php on line 211`

**Comment by Fivell** [comment]
@p-drolima , your account was not configured on sandbox,  to activate it  please sent email to support@didww.com

**Comment by p-drolima** [comment]
ha, ok :) my client has access to that not me. And he advised me use sandbox only, which I assumed it was active.

Thanks Igor. Have a good day!!

**Comment by p-drolima** [comment]
Hi Igor,

Sorry for reopening issue but I need further clarification here as we got a an email DIDWW and left me a bit confused in terms of implementing this.

Here it goes:

Dear Yakov Nissen,

Thank you for your wishes. We wish you best in new years as well.

Yes, API key is the same. The most important part is authentication key, how it is generated.
For sandbox:
$username = 'username@domain.com';
$key = '123456780909';
$auth_string = sha1($username.$key.'sandbox');

Also, WSDL address is https://sandbox-api.didww.com/api2/index.php?wsdl.

Here is the link with more information http://open.didww.com/index.php/Authentication_Key.
Here is the link with all functions list http://open.didww.com/index.php/DIDWW_API_2.0_Documentation#API_Functions

Your commercial API data won't be affected, if you will use proper information, which I explained above.

Let us know, if you have more questions.

Best Regards,
Edvardas Petrauskas

**Comment by p-drolima** [comment]
you implementation uses variables that enable sandbox and the auth key is generated by the code in sdk, correct?

am I missing something obvious here??

Thank you

**Comment by Fivell** [comment]
@p-drolima , yes you're right.

checkout https://github.com/didww/php-sdk/blob/master/src/Didww/API2/ApiClient.php#L138 and
https://github.com/didww/php-sdk/blob/master/src/Didww/API2/ApiCredentials.php#L172

**Comment by p-drolima** [comment]
yeh, that is the whole point of the SDK right :) I send DIDWW an email back regards to this. I feel this should be closed again and will continue my email communication with DIDWW.

Just to clarify, are you part of DIDWW setup team? or your involvement is just with this particular SDK?

**Comment by Fivell** [comment]
@p-drolima , I'm involved with this particular SDK.
