### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by akankov** [didww/php-sdk#9]
Uncaught exception 'Exception' with message 'Object of class stdClass could not be converted to string
/somethere/vendor/didww/php-sdk/src/Didww/API2/ApiClient.php 193'

**Comment by Fivell** [comment]
@akankov , thanks for your report, however it is hard to arrange now it is bug or not, would be nice to have full backtrace and some details. Line that you pointed in issue is about  [calling error_log](https://github.com/didww/php-sdk/blob/master/src/Didww/API2/ApiClient.php#L193)

If it is possible arguments for this method that cause Exception are required.

**Comment by Fivell** [comment]
closing as stale
